### ISSUE TITLE
Create a test lic server

### ISSUE THREAD

**Issue by perpetualintelligencegit** [perpetualintelligence/cli#15]
We should have a test license that users and use to quickly onboard the cli framework.

**Comment by pramodsubhedar** [comment]
We now have demo license capability (going live on 20-May-2022). Users can use demo license for quick onboarding and evaluation without creating an account. 

Demo License
https://www.perpetualintelligence.com/products/pidemo/licensing

Docs
https://docs.perpetualintelligence.com/articles/pi-demo/intro.html
