### ISSUE TITLE
Support declarative syntax for command and arguments

### ISSUE THREAD

**Issue by apspi** [perpetualintelligence/cli#24]
**Is your feature request related to a problem? Please describe.**
Its not convenient to declare all the command and argument descriptors using the DI methods. The code becomes difficult to debug and maintain.

**Describe the solution you'd like**
pi-cli must support declarative attributes that I can use to declare the commands and arguments with custom runner and checker.

**Describe alternatives you've considered**
A json file will be a good alternative as well, but based on docs that feature is not yet released.

**Additional context**
PerpetualIntelligence.Cli.2.6.1-rc

**Comment by asperpint** [comment]
@ameyasubhedar Thanks for contacting us.

The declarative syntax for CLI framework is in progress. You can see the initial code constructs [here](https://github.com/perpetualintelligence/cli/tree/main/src/PerpetualIntelligence.Cli/Commands/Declarative). Please feel free to provide your feedback.

The Json file support for command and argument descriptors is in roadmap but not yet planned.

**Comment by asperpint** [comment]
@pramodsubhedar, we need update docs for this feature as we develop it.

**Comment by asperpint** [comment]
Closed for Version 4.3.*
