### ISSUE TITLE
Support tags for the commands to find them easily

### ISSUE THREAD

**Issue by apspi** [perpetualintelligence/cli#25]
**Is your feature request related to a problem? Please describe.**
For products and services that have high number commands the tags will help users find the relevant commands.

Example:
```
az find blob
```

**Describe the solution you'd like**
Ability to specify tags for the commands and an OOTB find runner to search the command store and return the relevant commands.

**Comment by ameyasubhedar** [comment]
We also need an OOTB Help runner for commands and grouped commands. If you already know the name of the command, the --help argument for that command should get you more detailed information on the command, and for a command group, a list of the available subcommands. For example, here's how you can get a list of the subgroups and commands for managing blob storage:

```
az storage blob --help
```

**Comment by ameyasubhedar** [comment]
tags to resources to logically organize all the commands.

**Comment by perpetualintelligencegit** [comment]
Both tags and Help are supported on version 4.5.x. Closing in favor of #42
