### ISSUE TITLE
Improve the current mechanism to add commands and arguments to DI system

### ISSUE THREAD

**Issue by apspi** [perpetualintelligence/cli#31]
**Is your feature request related to a problem? Please describe.**
The current mechanism to add commands and arguments is very clunky and needs to be improved.

**Describe the solution you'd like**
Add dynamic builders that will provide easy method to configure the commands and arguments to the DI system.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by perpetualintelligencegit** [comment]
Thanks for your request, as part of refactoring to support multiple stores (such as in-memory, json, declarative) we will consider this request.

**Comment by asperpint** [comment]
Resolved in latest release.
