### ISSUE TITLE
IAsyncEventHandler not raising AfterCommandRunAsync during exception

### ISSUE THREAD

**Issue by ameyasubhedarats** [perpetualintelligence/cli#40]
**Describe the bug**
If the command's RunAsync method raises an exception, the AfterCommandRunAsync is not called. We need the ability to execute our code for each command run irrespective of any error or exception.

**Expected behavior**
An ability to execute begin and end command event handler irrespective of exception.

**Runtime**
 - OS: Linux
 - .NET 7.0.2
 - pi-cli 4.2.4-rc

**Comment by asperpint** [comment]
@ameyasubhedarats, thanks for reporting an issue. Looking at the current implementation, AfterCommandRunAsync will not be called if the RunAsync of a command runner raises an exception. The design intent is to call the After method only if the command run succeeds.

**Comment by ameyasubhedarats** [comment]
How do I ensure the application code is executed at the end of the command run with or without exception?

**Comment by asperpint** [comment]
We distinguish between command routing (router + handler + checker + runner + process result) and command run, which executes the command. The command run may fail in any of the routing- steps. What you are looking for is a Before and After command routing event. And this event can be made tolerant of exceptions.

**Comment by ameyasubhedarats** [comment]
AfterCommandRunAsync should be made tolerant of exceptions. @Nilavarasi-Ashika, do we have a use case to do performance profiling for a command run?

**Comment by asperpint** [comment]
In the case of profiling, don't you want to start and end only for a successful run ?

**Comment by ameyasubhedarats** [comment]
@asperpint, I don't understand the justification! Profiling is just an example. There could be other examples, such as creating an additional log at the command's start and releasing the resources at the end. In case of exception, the framework does not allow any mechanism to execute app code.

**Comment by asperpint** [comment]
@ameyasubhedarats, I am not disputing the ask. The Router Before and After event handling (exception tolerant) may be a more appropriate way to handle app-side allocation and cleanup. That way, we still have a way to execute post-command run app code only if the command run is successful.

**Comment by asperpint** [comment]
@ameyasubhedarats, @Nilavarasi-Ashika, The fix is ready for release v4.4.2-rc* Please feel free to review it in our repo and provide feedback.

**Comment by Nilavarasi-Ashika** [comment]
Exception in command parsing AfterCommandRouteAsync method getting the null values for Command and CommandRouterResult, in such case need to know command name which cause the exception.
@ameyasubhedarats @VijayakumarKothapalle @ChandramouliShridharan FYI
![image](https://github.com/perpetualintelligence/cli/assets/122000760/1b1fb478-6441-4ecc-95e7-23c6bc39d1c7)

**Comment by asperpint** [comment]
@Nilavarasi-Ashika , looks like you are too early in the routing. The Command object is constructed only if the handler, checker, and parser pass. We can provide you access to the CommandRoute instance but that will only provide you the raw command string access.
