### ISSUE TITLE
Documentation update for latest release

### ISSUE THREAD

**Issue by Nilavarasi-Ashika** [perpetualintelligence/cli#74]
**Describe the bug**
Update the documentation for latest release. 

**Expected behavior**
To understanding what are changes and update made in release.

**Comment by Nilavarasi-Ashika** [comment]
@ChandramouliShridharan @ameyasubhedarats @VijayakumarKothapalle FYI

**Comment by perpetualintelligencegit** [comment]
I am closing in favor of #42 Duplicate. 

@Nilavarasi-Ashika: Updating the documentation is part of our Sep-23 Milestone. In the meantime, if you have any questions, please don't hesitate to reach us with your priority support account.
